<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="84" started-at="2017-11-06T17:55:26Z" finished-at="2017-11-06T17:55:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="84" started-at="2017-11-06T17:55:26Z" finished-at="2017-11-06T17:55:26Z">
      <class name="com.TestNG.WebDriverClass.SoftAssertDemo">
        <test-method status="PASS" signature="hardassert()[pri:0, instance:com.TestNG.WebDriverClass.SoftAssertDemo@a12c19]" name="hardassert" duration-ms="29" started-at="2017-11-06T23:25:26Z" finished-at="2017-11-06T23:25:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hardassert -->
        <test-method status="FAIL" signature="softassert()[pri:0, instance:com.TestNG.WebDriverClass.SoftAssertDemo@a12c19]" name="softassert" duration-ms="11" started-at="2017-11-06T23:25:26Z" finished-at="2017-11-06T23:25:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [15] but found [12]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [15] but found [12]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.TestNG.WebDriverClass.SoftAssertDemo.softassert(SoftAssertDemo.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- softassert -->
      </class> <!-- com.TestNG.WebDriverClass.SoftAssertDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
